const combinator = [
  { name: "and", title: "AND" },
  { name: "or", title: "OR" },
  { name: "not", title: "NOT" },
];

const queryType = [
  { name: "select", title: "SELECT" },
  { name: "update", title: "UPDATE" },
  { name: "delete", title: "DELETE" },
];

const operators_by_type = {
  enum: ["=", "!=", "isNull", "isNotNull"],
  text: ["like", "notLike", "isNull", "isNotNull"],
  string: ["=", "!=", "like", "notLike", "isNull", "isNotNull"],
  integer: [
    "=",
    "!=",
    ">=",
    "<=",
    ">",
    "<",
    "between",
    "notBetween",
    "isNull",
    "isNotNull",
  ],
  boolean: ["isTrue", "isFalse"],
};

const map_operator = {
  "=": "=",
  "!=": "!=",
  ">": ">",
  ">=": ">=",
  "<": "<",
  "<=": "<=",
  in: "IN",
  notIn: "NOT IN",
  between: "BETWEEN",
  notBetween: "NOT BETWEEN",
  isNull: "IS NULL",
  isNotNull: "IS NOT NULL",
  like: "LIKE",
  notLike: "NOT LIKE",
};

const operators = [
  { name: "=", title: "equals" },
  { name: "!=", title: "not equal" },
  { name: ">", title: "greater than" },
  { name: ">=", title: "greater or equal" },
  { name: "<", title: "less than" },
  { name: "<=", title: "less or equal" },
  { name: "in", title: "in" },
  { name: "between", title: "between" },
  { name: "notBetween", title: "not Between" },
  { name: "notIn", title: "not in" },
  { name: "isNull", title: "is null" },
  { name: "isNotNull", title: "is not null" },
  { name: "like", title: "contains" },
  { name: "notLike", title: "doesn't contain" },
  { name: "isTrue", title: "is true" },
  { name: "isFalse", title: "is false" },
];

const metaModals = [
  {
    name: 'Address',
    fullName: 'com.example.db.Address',
    metaFields: [
      {
        name: 'state',
        id: 626,
        $version: 0,
      },
      {
        name: 'id',
        id: 625,
        $version: 0,
      },
      {
        name: 'contact',
        id: 624,
        $version: 0,
      },
      {
        name: 'street',
        id: 623,
        $version: 0,
      },
      {
        name: 'city',
        id: 615,
        $version: 0,
      },
      {
        name: 'country',
        id: 612,
        $version: 0,
      },
      {
        name: 'zip',
        id: 611,
        $version: 0,
      },
      {
        name: 'area',
        id: 609,
        $version: 0,
      },
    ],
    id: 41,
    version: 0,
  },
  {
    name: 'Circle',
    fullName: 'com.example.db.Circle',
    metaFields: [
      {
        name: 'id',
        id: 655,
        $version: 0,
      },
      {
        name: 'name',
        id: 654,
        $version: 0,
      },
      {
        name: 'code',
        id: 651,
        $version: 0,
      },
    ],
    id: 44,
    version: 0,
  },
  {
    name: 'Company',
    fullName: 'com.example.db.Company',
    metaFields: [
      {
        name: 'employees',
        id: 649,
        $version: 0,
      },
      {
        name: 'id',
        id: 648,
        $version: 0,
      },
      {
        name: 'name',
        id: 647,
        $version: 0,
      },
      {
        name: 'notes',
        id: 637,
        $version: 0,
      },
      {
        name: 'code',
        id: 635,
        $version: 0,
      },
    ],
    id: 43,
    version: 0,
  },
  {
    name: 'Contact',
    fullName: 'com.example.db.Contact',
    metaFields: [
      {
        name: 'email',
        id: 694,
        $version: 0,
      },
      {
        name: 'id',
        id: 693,
        $version: 0,
      },
      {
        name: 'company',
        id: 692,
        $version: 0,
      },
      {
        name: 'phone',
        id: 690,
        $version: 0,
      },
      {
        name: 'firstName',
        id: 686,
        $version: 0,
      },
      {
        name: 'emails',
        id: 682,
        $version: 0,
      },
      {
        name: 'title',
        id: 674,
        $version: 0,
      },
      {
        name: 'dateOfBirth',
        id: 669,
        $version: 0,
      },
      {
        name: 'phones',
        id: 667,
        $version: 0,
      },
      {
        name: 'fullName',
        id: 666,
        $version: 0,
      },
      {
        name: 'circles',
        id: 665,
        $version: 0,
      },
      {
        name: 'notes',
        id: 663,
        $version: 0,
      },
      {
        name: 'addresses',
        id: 662,
        $version: 0,
      },
      {
        name: 'lastName',
        id: 661,
        $version: 0,
      },
    ],
    id: 45,
    version: 0,
  },
  {
    name: 'Country',
    fullName: 'com.example.db.Country',
    metaFields: [
      {
        name: 'id',
        id: 595,
        $version: 0,
      },
      {
        name: 'name',
        id: 594,
        $version: 0,
      },
      {
        name: 'code',
        id: 591,
        $version: 0,
      },
    ],
    id: 39,
    version: 0,
  },
  {
    name: 'Email',
    fullName: 'com.example.db.Email',
    metaFields: [
      {
        name: 'email',
        id: 689,
        $version: 0,
      },
      {
        name: 'id',
        id: 687,
        $version: 0,
      },
      {
        name: 'contact',
        id: 683,
        $version: 0,
      },
    ],
    id: 46,
    version: 0,
  },
];

const metaFields = [
  {
    modal: 'com.example.db.Contact',
    fields: [
      {
        virtual: true,
        readonly: true,
        name: 'email',
        type: 'STRING',
        title: 'Email',
      },
      {
        readonly: true,
        hidden: true,
        name: 'id',
        type: 'LONG',
        title: 'Id',
        primary: true,
      },
      {
        massUpdate: true,
        targetName: 'name',
        targetSearch: ['name', 'code'],
        name: 'company',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'Company',
        target: 'com.example.db.Company',
      },
      {
        virtual: true,
        readonly: true,
        name: 'phone',
        type: 'STRING',
        title: 'Phone',
      },
      {
        name: 'firstName',
        type: 'STRING',
        title: 'First name',
        required: true,
      },
      {
        targetName: 'email',
        targetSearch: ['email'],
        name: 'emails',
        perms: null,
        type: 'ONE_TO_MANY',
        title: 'Emails',
        mappedBy: 'contact',
        target: 'com.example.db.Email',
      },
      {
        targetName: 'name',
        targetSearch: ['name', 'code'],
        name: 'title',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'Title',
        target: 'com.example.db.Title',
      },
      {
        name: 'dateOfBirth',
        type: 'DATE',
        title: 'Date of birth',
      },
      {
        targetName: 'phone',
        targetSearch: ['phone'],
        name: 'phones',
        perms: null,
        type: 'ONE_TO_MANY',
        title: 'Phones',
        mappedBy: 'contact',
        target: 'com.example.db.Phone',
      },
      {
        virtual: true,
        nameSearch: ['firstName', 'lastName'],
        readonly: true,
        nameColumn: true,
        name: 'fullName',
        type: 'STRING',
        title: 'Full name',
      },
      {
        targetName: 'name',
        targetSearch: ['name', 'code'],
        name: 'circles',
        perms: null,
        type: 'MANY_TO_MANY',
        title: 'Circles',
        target: 'com.example.db.Circle',
      },
      {
        name: 'notes',
        type: 'TEXT',
        title: 'Notes',
      },
      {
        targetName: null,
        targetSearch: [],
        name: 'addresses',
        perms: null,
        type: 'ONE_TO_MANY',
        title: 'Addresses',
        mappedBy: 'contact',
        target: 'com.example.db.Address',
      },
      {
        name: 'lastName',
        type: 'STRING',
        title: 'Last name',
        required: true,
      },
    ],
  },
  {
    modal: 'com.example.db.Address',
    fields: [
      {
        name: 'state',
        type: 'STRING',
        title: 'State',
      },
      {
        readonly: true,
        hidden: true,
        name: 'id',
        type: 'LONG',
        title: 'Id',
        primary: true,
      },
      {
        targetName: 'fullName',
        targetSearch: ['fullName', 'firstName', 'lastName'],
        name: 'contact',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'Contact',
        required: true,
        target: 'com.example.db.Contact',
      },
      {
        name: 'street',
        maxSize: 255,
        type: 'STRING',
        title: 'Street',
        required: true,
      },
      {
        name: 'city',
        type: 'STRING',
        title: 'City',
      },
      {
        targetName: 'name',
        targetSearch: ['name', 'code'],
        name: 'country',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'Country',
        target: 'com.example.db.Country',
      },
      {
        name: 'zip',
        type: 'STRING',
        title: 'Zip',
      },
      {
        name: 'area',
        maxSize: 255,
        type: 'STRING',
        title: 'Area',
      },
    ],
  },
  {
    modal: 'com.example.db.Circle',
    fields: [
      {
        readonly: true,
        hidden: true,
        name: 'id',
        type: 'LONG',
        title: 'Id',
        primary: true,
      },
      {
        nullable: true,
        unique: true,
        name: 'name',
        maxSize: 2147483647,
        minSize: 2,
        type: 'STRING',
        title: 'Name',
        required: true,
      },
      {
        nullable: true,
        unique: true,
        name: 'code',
        maxSize: 2147483647,
        minSize: 2,
        type: 'STRING',
        title: 'Code',
        required: true,
      },
    ],
  },
  {
    modal: 'com.example.db.Company',
    fields: [
      {
        targetName: 'fullName',
        targetSearch: ['fullName', 'firstName', 'lastName'],
        name: 'employees',
        perms: null,
        type: 'ONE_TO_MANY',
        title: 'Employees',
        mappedBy: 'company',
        target: 'com.example.db.Contact',
      },
      {
        readonly: true,
        hidden: true,
        name: 'id',
        type: 'LONG',
        title: 'Id',
        primary: true,
      },
      {
        nullable: true,
        unique: true,
        name: 'name',
        maxSize: 2147483647,
        minSize: 2,
        type: 'STRING',
        title: 'Name',
        required: true,
      },
      {
        name: 'notes',
        type: 'TEXT',
        title: 'Notes',
      },
      {
        nullable: true,
        unique: true,
        name: 'code',
        maxSize: 2147483647,
        minSize: 2,
        type: 'STRING',
        title: 'Code',
        required: true,
      },
    ],
  },
  {
    modal: 'com.example.db.Country',
    fields: [
      {
        readonly: true,
        hidden: true,
        name: 'id',
        type: 'LONG',
        title: 'Id',
        primary: true,
      },
      {
        nullable: true,
        unique: true,
        name: 'name',
        maxSize: 2147483647,
        minSize: 2,
        type: 'STRING',
        title: 'Name',
        required: true,
      },
      {
        nullable: true,
        unique: true,
        name: 'code',
        maxSize: 2147483647,
        minSize: 2,
        type: 'STRING',
        title: 'Code',
        required: true,
      },
    ],
  },
  {
    modal: 'com.example.db.Email',
    fields: [
      {
        nullable: true,
        nameColumn: true,
        unique: true,
        name: 'email',
        type: 'STRING',
        title: 'Email',
        required: true,
      },
      {
        readonly: true,
        hidden: true,
        name: 'id',
        type: 'LONG',
        title: 'Id',
        primary: true,
      },
      {
        targetName: 'fullName',
        targetSearch: ['fullName', 'firstName', 'lastName'],
        name: 'contact',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'Contact',
        required: true,
        target: 'com.example.db.Contact',
      },
    ],
  },
];

const data = [
  {
    model: 'com.example.db.Circle',
    data: [
      { id: 1, title: 'family', name: 'Family' },
      { id: 2, title: 'business', name: 'Business' },
    ],
  },
  {
    model: 'com.example.db.Address',
    data: [],
  },
  {
    model: 'com.example.db.Company',
    data: [
      { id: 1, title: 'xyz', name: 'XYZ' },
      { id: 2, title: 'abc', name: 'ABC' },
    ],
  },
  {
    model: 'com.example.db.Contact',
    data: [],
  },
  {
    model: 'com.example.db.Country',
    data: [
      { id: 1, title: 'ind', name: 'India' },
      { id: 2, title: 'ger', name: 'Germany' },
    ],
  },
  {
    model: 'com.example.db.Email',
    data: [],
  },
];
export {
  combinator,
  queryType,
  operators,
  operators_by_type,
  map_operator,
  metaModals,
  metaFields,
  data,
};